#!/bin/bash

set -e

NAME=Sia

# shellcheck disable=SC1090
. "$(dirname "$0")"/docker.bash

start() {
    SIA_HOST=127.0.0.1
    SIA_PORT=9980
    SIA_CONN="${SIA_HOST}:${SIA_PORT}"

    docker run --rm -d --name "$NAME" \
            -p "${SIA_CONN}:${SIA_PORT}" \
            nebulouslabs/siaantfarm

    # wait for Sia to warm up (prevents EOF errors)
    sleep 60

    # confirm backend type in the generated rclone.conf
    echo "type=sia"
    # override keys in the Sia section of generated rclone.conf
    echo "api_url=http://${SIA_CONN}/"
    # hint test harness where to probe for connection
    echo "_connect=${SIA_CONN}"
}

stop() {
    if status ; then
        docker logs "$NAME" >> sia-test.log 2>&1
        docker kill "$NAME"
        echo "${NAME} stopped"
    fi
}

# shellcheck disable=SC1090
. "$(dirname "$0")"/run.bash
